language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t csakamaki/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true csakamaki/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-react-env"
#   bucket_name: "elasticbeanstalk-us-west-2-<id_num>"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
